# Exercise the public CLI, not harness implementation details. Work outside both
# the source and build trees; every child invocation gets its own harness root.
if(WIN32)
    file(TO_CMAKE_PATH "$ENV{TEMP}" temp)
else()
    set(temp "/tmp")
endif()
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef suffix)
set(work "${temp}/pf-smoke-contract-${suffix}")
file(MAKE_DIRECTORY "${work}")

function(invoke executable status expected)
    execute_process(COMMAND "${executable}" ${ARGN}
        WORKING_DIRECTORY "${work}" RESULT_VARIABLE result
        OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 15)
    if(NOT "${result}" STREQUAL "${status}")
        message(FATAL_ERROR "${ARGN}: expected status ${status}, got ${result}\n${out}\n${err}")
    endif()
    if(status EQUAL 2)
        if(NOT out STREQUAL "" OR NOT err MATCHES "^ERROR ")
            message(FATAL_ERROR "Misuse must only report on stderr: ${out} / ${err}")
        endif()
    else()
        if(NOT err STREQUAL "" OR NOT out MATCHES "${expected}")
            message(FATAL_ERROR "Unexpected result: ${out} / ${err}; expected ${expected}")
        endif()
    endif()
    set(output "${out}" PARENT_SCOPE)
endfunction()

invoke("${PROBE}" 0 "^pass\nfail\nskip\nunknown-exception\nmissing-fixture\nafter\npaths\nfailed-paths\n$" --list)
invoke("${PROBE}" 0 "^PASS harness pass\nSUMMARY harness pass=1 fail=0 skip=0\n$" --check pass)
invoke("${PROBE}" 1 "^FAIL harness fail: deliberate failure\nSUMMARY harness pass=0 fail=1 skip=0\n$" --check fail)
invoke("${PROBE}" 0 "^SKIP harness skip: optional external capability unavailable [(]synthetic[)]\nSUMMARY harness pass=0 fail=0 skip=1\n$" --check skip)
invoke("${PROBE}" 1 "^FAIL harness unknown-exception: unknown exception\nSUMMARY harness pass=0 fail=1 skip=0\n$" --check unknown-exception)
invoke("${PROBE}" 1 "^FAIL harness missing-fixture: Missing required fixture: .*\nSUMMARY harness pass=0 fail=1 skip=0\n$" --check missing-fixture)
invoke("${PROBE}" 1 "SUMMARY harness pass=3 fail=4 skip=1\n$")
if(NOT output MATCHES "PASS harness after\n")
    message(FATAL_ERROR "Runner did not continue after failed checks")
endif()
foreach(arguments IN ITEMS "--bogus" "--check" "--check;absent" "--list;extra" "--check;pass;extra" "pass")
    invoke("${PROBE}" 2 "" ${arguments})
endforeach()

foreach(check IN ITEMS paths failed-paths)
    if(check STREQUAL "paths")
        set(status 0)
    else()
        set(status 1)
    endif()
    invoke("${PROBE}" ${status} "SUMMARY harness" --check ${check})
    string(REGEX MATCH "ROOT ([^\n]+)" root "${output}")
    if(NOT root OR EXISTS "${CMAKE_MATCH_1}")
        message(FATAL_ERROR "Temporary root not reported or not cleaned: ${output}")
    endif()
endforeach()

if(WIN32)
    invoke("${PROBE}" 1 "PASS harness leaked-handle\nFAIL harness cleanup: Cannot clean smoke temporary root: .*\nSUMMARY harness pass=1 fail=1 skip=0\n$" --cleanup-failure)
    string(REGEX MATCH "ROOT ([^\n]+)" root "${output}")
    if(NOT root OR NOT EXISTS "${CMAKE_MATCH_1}/open-handle.txt")
        message(FATAL_ERROR "Leaked handle was not diagnosed: ${output}")
    endif()
    # The child has exited and released its deliberately leaked handle.
    file(REMOVE_RECURSE "${CMAKE_MATCH_1}")
endif()

# The full Simulation inventory belongs to SimulationContract.cmake.
invoke("${SIMULATION}" 0 "^PASS simulation observation\nSUMMARY simulation pass=1 fail=0 skip=0\n$" --check observation)
invoke("${SIMULATION}" 2 "" --check absent)
file(REMOVE_RECURSE "${work}")
