# Public Render CLI from an empty directory outside the source/build trees.
if(WIN32)
    set(temp "$ENV{TEMP}")
else()
    set(temp "/tmp")
endif()
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef suffix)
set(work "${temp}/pf-render-contract-${suffix}")
file(MAKE_DIRECTORY "${work}")

function(invoke status expected)
    execute_process(COMMAND "${RENDER}" ${ARGN}
        WORKING_DIRECTORY "${work}" RESULT_VARIABLE result
        OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 15)
    if(NOT "${result}" STREQUAL "${status}")
        message(FATAL_ERROR "${ARGN}: expected ${status}, got ${result}\n${out}\n${err}")
    endif()
    if(status EQUAL 2)
        if(NOT out STREQUAL "" OR NOT err MATCHES "^ERROR render:")
            message(FATAL_ERROR "Unexpected misuse output: ${out} / ${err}")
        endif()
    elseif(NOT err STREQUAL "" OR NOT out MATCHES "${expected}")
        message(FATAL_ERROR "Unexpected result: ${out} / ${err}")
    endif()
endfunction()

invoke(0 "^walls\nagentPaths\ncarriageDoors\ncarriageImages\n$" --list)
invoke(0 "^PASS render walls\nPASS render agentPaths\nPASS render carriageDoors\nPASS render carriageImages\nSUMMARY render pass=4 fail=0 skip=0\n$")
foreach(name IN ITEMS walls agentPaths carriageDoors carriageImages)
    invoke(0 "^PASS render ${name}\nSUMMARY render pass=1 fail=0 skip=0\n$" --check "${name}")
endforeach()
foreach(arguments IN ITEMS "--bogus" "--check" "--check;absent" "--list;extra" "--check;walls;extra")
    invoke(2 "" ${arguments})
endforeach()
file(GLOB artifacts "${work}/*" "${work}/.*")
if(artifacts)
    message(FATAL_ERROR "CPU-only rendering wrote working-directory files: ${artifacts}")
endif()
file(REMOVE_RECURSE "${work}")
