#include "Formats.h"
#include "Infrastructure.h"
#include "Smoke.h"
#include "WorldChecks.h"

namespace
{
	constexpr smoke::Check checks[] = {
		{ "yaml-primitives", persistence::stringYamlRoundTripsPrimitiveValues },
		{ "binary-contract", persistence::binarySerializerHonoursTheSerializerContract },
		{ "yaml-file", persistence::fileYamlRoundTrips },
		{ "transactional-bytes", persistence::transactionalWriterPreservesOpaqueBytes },
		{ "world-document-formats", persistence::worldDocumentsUseTheirExactSuffixFormat },
		{ "yaml-errors", persistence::malformedValuesAndInvalidUsageThrowUsefulErrors },
		{ "checked-in-world", persistence::checkedInYamlWorldLoads },
		{ "document-paths", persistence::worldDocumentPathsUseExactSuffixes },
		{ "transactional-late-failure", persistence::lateWriteFailurePreservesThePreviousSaveFile },
		{ "transactional-predictable-path", persistence::saveNeverTouchesAPredictableTemporaryPath },
		{ "transactional-symlink-target", persistence::saveThroughSymlinkUpdatesItsTarget },
		{ "transactional-symlink-temp", persistence::saveNeverFollowsASymlinkedTemporaryPath },
		{ "transactional-permissions", persistence::savePreservesExistingFilePermissions },
		{ "transactional-concurrent", persistence::concurrentSavesCommitOnlyCompleteDocuments },
		{ "save-dirty-state", persistence::failedSavePreservesUnsavedChangesState },
		{ "serializable-modification-state", persistence::serializableTracksModificationState },
		{ "recent-documents-restart", persistence::recentFilesPersistAcrossStartup },
		{ "recent-documents-missing", persistence::missingRecentFilesCanBeRemovedPersistently },
		{ "worldRoundTripsAuthoredStateAndAgents", persistence::worldRoundTripsAuthoredStateAndAgents },
		{ "legacyWorldYamlStillLoads", persistence::legacyWorldYamlStillLoads },
		{ "legacyVersion3WorldYamlStillLoadsWithDefaultLayers", persistence::legacyVersion3WorldYamlStillLoadsWithDefaultLayers },
		{ "version4WorldYamlStillLoads", persistence::version4WorldYamlStillLoads },
		{ "layerFieldsAcceptLegacyNamesAndIndices", persistence::layerFieldsAcceptLegacyNamesAndIndices },
		{ "agentRestoreRejectsMalformedPositions", persistence::agentRestoreRejectsMalformedPositions },
		{ "agentRestoreRejectsBackgroundAndUnreachableDestination", persistence::agentRestoreRejectsBackgroundAndUnreachableDestination },
		{ "worldLayerNamesRoundTrip", persistence::worldLayerNamesRoundTrip },
		{ "addedLayersAppendToTheBackAndRoundTrip", persistence::addedLayersAppendToTheBackAndRoundTrip },
		{ "layerCountIsCappedAtCoreMaxLayers", persistence::layerCountIsCappedAtCoreMaxLayers },
		{ "oversizedWorldDimensionsAreRefusedBeforeCellAccess", persistence::oversizedWorldDimensionsAreRefusedBeforeCellAccess },
		{ "levelsHaveNamesLimitsAndCascadingDeletion", persistence::levelsHaveNamesLimitsAndCascadingDeletion },
		{ "deletingAMiddleLayerCompactsTheLayersAboveIt", persistence::deletingAMiddleLayerCompactsTheLayersAboveIt },
		{ "deletingTheFrontLayerRemovesTransitsOneLayerBehind", persistence::deletingTheFrontLayerRemovesTransitsOneLayerBehind },
		{ "layerDeletionPreservesAuthoredRecordDependencies", persistence::layerDeletionPreservesAuthoredRecordDependencies },
		{ "layerDeletionKeepsAtLeastTwoLayers", persistence::layerDeletionKeepsAtLeastTwoLayers },
		{ "locationEditsArePlannedAndAppliedAtomically", persistence::locationEditsArePlannedAndAppliedAtomically },
		{ "editedShuttleRoundTripsWithoutSchemaChanges", persistence::editedShuttleRoundTripsWithoutSchemaChanges },
		{ "physicalControlsPreferDistinctWallPositions", persistence::physicalControlsPreferDistinctWallPositions },
		{ "platformLiftStopDurationRoundTrips", persistence::platformLiftStopDurationRoundTrips },
		{ "enclosedLiftsSupportMultiLevelRooms", persistence::enclosedLiftsSupportMultiLevelRooms },
		{ "stopDerivingAddLiftRejectsInvalidLayerIndex", persistence::stopDerivingAddLiftRejectsInvalidLayerIndex },
		{ "stairwellSectorsAreCanvasSelectable", persistence::stairwellSectorsAreCanvasSelectable },
		{ "staircasesConnectAdjacentCorridorsAndRoundTrip", persistence::staircasesConnectAdjacentCorridorsAndRoundTrip },
		{ "laddersCanBeValidatedEditedAndDeleted", persistence::laddersCanBeValidatedEditedAndDeleted },
		{ "stairwellsCanBeValidatedEditedAndDeleted", persistence::stairwellsCanBeValidatedEditedAndDeleted },
		{ "stairwellEditsReplayLocationsBeforeTransits", persistence::stairwellEditsReplayLocationsBeforeTransits },
		{ "stairwellEditsReplayWalkwaysBeforeTransits", persistence::stairwellEditsReplayWalkwaysBeforeTransits },
		{ "ladderEditsReplayLocationsBeforeTransits", persistence::ladderEditsReplayLocationsBeforeTransits },
		{ "staircaseEditsReplayLocationsBeforeTransits", persistence::staircaseEditsReplayLocationsBeforeTransits },
		{ "bulkheadDoorsSupportIndependentObjectEditing", persistence::bulkheadDoorsSupportIndependentObjectEditing },
		{ "doorOpeningStyleIsAuthoredPersistedAndLegacyDefaulted", persistence::doorOpeningStyleIsAuthoredPersistedAndLegacyDefaulted },
		{ "doorHeightPersistsAndIsLimitedToRooms", persistence::doorHeightPersistsAndIsLimitedToRooms },
		{ "doorOpenLeftPersistsThroughEveryEditorPath", persistence::doorOpenLeftPersistsThroughEveryEditorPath },
		{ "doorOpenRightPersistsThroughEveryEditorPath", persistence::doorOpenRightPersistsThroughEveryEditorPath },
		{ "doorOpenApartPersistsThroughEveryEditorPath", persistence::doorOpenApartPersistsThroughEveryEditorPath },
		{ "liftDoorsDefaultToOpenApartWhileOtherDoorsKeepOpenUp", persistence::liftDoorsDefaultToOpenApartWhileOtherDoorsKeepOpenUp },
		{ "doorStyleMapsAdvanceTheSchemaVersionAndLegacySixStillLoads", persistence::doorStyleMapsAdvanceTheSchemaVersionAndLegacySixStillLoads },
		{ "liftStopDoorStyleOverridesArePerStopAndPersist", persistence::liftStopDoorStyleOverridesArePerStopAndPersist },
		{ "liftCreationStopDoorStylesAreAuthoredAndPersist", persistence::liftCreationStopDoorStylesAreAuthoredAndPersist },
		{ "liftShortStopDoorStyleVectorEditPreservesEarlierOverrides", persistence::liftShortStopDoorStyleVectorEditPreservesEarlierOverrides },
		{ "liftCarKeepsItsShaftRelativeLevelWhenExtendedDownward", persistence::liftCarKeepsItsShaftRelativeLevelWhenExtendedDownward },
		{ "liftDoorStylesFollowStopsWhenTheLiftMovesOrResizes", persistence::liftDoorStylesFollowStopsWhenTheLiftMovesOrResizes },
		{ "liftDoorStylesReconcileWhenStopsChange", persistence::liftDoorStylesReconcileWhenStopsChange },
		{ "shuttleDoorStyleOverridesAreIndividualAndPersist", persistence::shuttleDoorStyleOverridesAreIndividualAndPersist },
		{ "shuttleDoorStylesSurviveShuttleMovement", persistence::shuttleDoorStylesSurviveShuttleMovement },
		{ "shuttleDoorStylesReconcileWhenStopsChange", persistence::shuttleDoorStylesReconcileWhenStopsChange },
		{ "shuttleDoorStylesReconcileWhenCarriageAndDoorLayoutChanges", persistence::shuttleDoorStylesReconcileWhenCarriageAndDoorLayoutChanges },
		{ "shuttleVehicleEditsRejectZeroValuedFields", persistence::shuttleVehicleEditsRejectZeroValuedFields },
		{ "layerHelperApiIsConsistentWithLayerCount", persistence::layerHelperApiIsConsistentWithLayerCount },
		{ "graphConstructionWalksEveryAdjacentLayerPair", persistence::graphConstructionWalksEveryAdjacentLayerPair },
		{ "thresholdsAndTransitsPairTheirOwnAdjacentLayerPair", persistence::thresholdsAndTransitsPairTheirOwnAdjacentLayerPair },
		{ "doorAndWindowRemovalWorksOnDeepLayerPairs", persistence::doorAndWindowRemovalWorksOnDeepLayerPairs },
		{ "shuttleDoorCandidatesAreFoundOnTheShuttleLayer", persistence::shuttleDoorCandidatesAreFoundOnTheShuttleLayer },
		{ "candidateReplayIncludesAllLayers", persistence::candidateReplayIncludesAllLayers },
		{ "liftEditsUseTheLiftsOwnLayer", persistence::liftEditsUseTheLiftsOwnLayer },
		{ "shuttleEditsUseTheShuttlesOwnLayer", persistence::shuttleEditsUseTheShuttlesOwnLayer },
		{ "shuttleDeletionRemovesWindowsOverTheShuttleItself", persistence::shuttleDeletionRemovesWindowsOverTheShuttleItself },
		{ "ladderEditsUseTheLaddersOwnLayer", persistence::ladderEditsUseTheLaddersOwnLayer },
		{ "stairwellEditsUseTheStairwellsOwnLayer", persistence::stairwellEditsUseTheStairwellsOwnLayer },
		{ "staircaseEditsReturnTheStaircaseOwnLayer", persistence::staircaseEditsReturnTheStaircaseOwnLayer },
		{ "restorationPreservesStatePathsAndLifetimes", persistence::restorationPreservesStatePathsAndLifetimes },
	};
}

int main(int argc, char** argv)
{
	return smoke::main("persistence", checks, argc, argv);
}
